package listeners;

import org.testng.IAnnotationTransformer;
import org.testng.annotations.ITestAnnotation;

import java.lang.reflect.Constructor;
import java.lang.reflect.Method;

/*
 * Wires RetryAnalyzer onto Cucumber's generated runScenario test method. Registered via
 * testng.xml <listeners> since runScenario is generated by AbstractTestNGCucumberTests and
 * can't be annotated directly with @Test(retryAnalyzer = ...).
 */
public class AnnotationTransformer implements IAnnotationTransformer {

    @Override
    public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {
        annotation.setRetryAnalyzer(RetryAnalyzer.class);
    }
}
